# Generated by Django 2.2.28 on 2023-02-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(default=0, upload_to='')),
                ('bio', models.TextField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(default=0, upload_to='')),
                ('bio', models.TextField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(default=0, upload_to='')),
                ('cuisine', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True, null=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_server.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('max_score', models.IntegerField(default=0)),
                ('ginal_score', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_server.Customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_server.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('user_type', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vocher_code', models.CharField(blank=True, max_length=128, null=True)),
                ('value', models.IntegerField(default=0)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_server.Customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_server.Restaurant')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='survey_server.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey_server.User')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey_server.Voucher'),
        ),
    ]
