# Generated by Django 4.1.7 on 2023-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='ginal_score',
            new_name='final_score',
        ),
        migrations.AddField(
            model_name='survey',
            name='ordered_starter',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='presentation_starter',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='size_starter',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='starter_time',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='variety_starter',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
