# Generated by Django 4.1.7 on 2023-03-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0007_auto_20230306_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='customer_service_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='food_quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='hygiene_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_customer_service_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_food_quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_hygiene_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_menu_variety_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_value_for_money_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='menu_variety_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='value_for_money_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
