# Generated by Django 4.1.7 on 2023-03-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0010_rename_vocher_code_voucher_voucher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='voucher',
        ),
        migrations.AddField(
            model_name='survey',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='voucher_is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='voucher_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='voucher_value',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
