# Generated by Django 4.1.7 on 2023-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0011_remove_survey_voucher_survey_voucher_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(null=True, upload_to='menus/<django.db.models.fields.SlugField>'),
        ),
    ]
