# Generated by Django 4.1.7 on 2023-03-11 17:07

from django.db import migrations, models
import survey_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0012_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(default=0, upload_to=survey_server.models.menu_upload_to, validators=[survey_server.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
