# Generated by Django 4.1.7 on 2023-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0015_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_slug',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
