# Generated by Django 4.1.7 on 2023-03-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0016_menuitem_restaurant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant_slug',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='survey_server.restaurant'),
            preserve_default=False,
        ),
    ]
