# Generated by Django 4.1.7 on 2023-03-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0017_remove_menuitem_restaurant_slug_menuitem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('starters', 'Starter'), ('mains', 'Main'), ('desserts', 'Dessert'), ('drinks', 'Drink')], max_length=10),
        ),
    ]
