# Generated by Django 4.1.7 on 2023-03-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0018_alter_menuitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='max_score',
        ),
    ]
