# Generated by Django 4.1.7 on 2023-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0019_remove_survey_final_score_remove_survey_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='dessert_order',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='drink_order',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='main_order',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='survey',
            name='starter_order',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
