# Generated by Django 2.2.28 on 2023-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0025_restaurant_voucher_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='over_all_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
