# Generated by Django 2.2.28 on 2023-03-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0026_auto_20230320_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='over_all_score',
        ),
    ]
