# Generated by Django 4.1.7 on 2023-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0028_alter_menuitem_id_alter_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='voucher_value',
            field=models.IntegerField(default=15),
        ),
    ]
