# Generated by Django 4.1.7 on 2023-03-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0029_manager_voucher_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='voucher_value',
        ),
    ]
