# Generated by Django 4.1.7 on 2023-03-24 15:59

from django.db import migrations, models
import survey_server.upload


class Migration(migrations.Migration):

    dependencies = [
        ('survey_server', '0030_remove_manager_voucher_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default=0, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(upload_to='menus', validators=[survey_server.upload.validate_file_extension]),
        ),
    ]
